default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: dipendra
  password: dipendra
  host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: college_project_development

test:
  <<: *default
  database: college_project_test

production:
  <<: *default
  database: college_project_production

